In [1]:
import tensorflow as tf
import keras
import keras.backend as K
from keras.metrics import BinaryCrossentropy
from keras.losses import BinaryCrossentropy

from keras.activations import sigmoid

In [2]:
tf.config.list_physical_devices('GPU')

[]

In [14]:
foo = tf.constant([-10, -5, 0.0, 5, 10], dtype = tf.float32)
sigmoid(foo).numpy()

array([4.5399931e-05, 6.6928566e-03, 5.0000000e-01, 9.9330711e-01,
       9.9995458e-01], dtype=float32)

In [18]:
import scipy
scipy.special.expit(43)

1.0

In [ ]:
array([ 0.,  0.,  0.,  5., 10.], dtype=float32)
>>> tf.keras.activations.relu(foo, alpha=0.5).numpy()
array([-5. , -2.5,  0. ,  5. , 10. ], dtype=float32)
>>> tf.keras.activations.relu(foo, max_value=5).numpy()
array([0., 0., 0., 5., 5.], dtype=float32)
>>> tf.keras.activations.relu(foo, threshold=5).numpy()
array([-0., -0.,  0.,  0., 10.], dtype=float32)

## The model 

In [20]:
from keras.initializers import RandomNormal, Zeros
from keras.layers import Dense, Dropout, Conv1D, Input, Reshape, Softmax, Flatten, Concatenate, BatchNormalization
from keras.layers import  Lambda, Multiply, Dot, GaussianNoise, Add, Average, Subtract
from keras.models import Sequential, Model
from keras.models import load_model
from keras.optimizers import SGD, Adagrad, Adadelta
from keras.regularizers import l1_l2, l1, l2
from keras.utils import plot_model

import keras.backend as K
import numpy as np
import pandas as pd
import logging
import keras
from keras.layers.pooling import AveragePooling1D, MaxPool1D
from keras.layers.core import Activation


In [21]:
import MOAL1000.dataprep as dataprep
import MOAL1000.dataload as dataload

X_train, X_holdout, y_train, y_holdout = dataload.load_data_v1()

In [26]:
inputs = Input(shape=(978, 7,))

layer1 = Dense(10)(inputs)
layer2 = Dense(1)(layer1)

layer3 = Flatten()(layer2)
outputs = Dense(50)(layer3)
model = Model(inputs=inputs, outputs=outputs)

In [28]:
model.summary()

Model: "model_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_3 (InputLayer)         [(None, 978, 7)]          0         
_________________________________________________________________
dense_6 (Dense)              (None, 978, 10)           80        
_________________________________________________________________
dense_7 (Dense)              (None, 978, 1)            11        
_________________________________________________________________
flatten_2 (Flatten)          (None, 978)               0         
_________________________________________________________________
dense_8 (Dense)              (None, 50)                48950     
Total params: 49,041
Trainable params: 49,041
Non-trainable params: 0
_________________________________________________________________


In [31]:
model(X_train).numpy().shape

(3366, 50)

In [9]:
from keras import backend as K
K._get_available_gpus()

[]

In [2]:
import tensorflow as tf; print("Num GPUs Available: ", len(tf.config.list_physical_devices("GPU")))

Num GPUs Available:  0


In [12]:
import tensorflow as tf
from tensorflow.keras.utils import plot_model

In [46]:
import numpy as np
import pandas as pd
a = pd.DataFrame(np.random.random((10,5)))
a = a.astype(str).applymap(lambda s:s[:6])
a.to_csv("tmp.txt", sep="\t")